services:
  # # Databse
  # mongo:
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: usr
  #     MONGO_INITDB_ROOT_PASSWORD: pwd
  #     MONGO_INITDB_DATABASE: Master

  # # Database Interface (comment out if not needed)
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: usr
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: pwd
  #     ME_CONFIG_MONGODB_URL: mongodb://usr:pwd@mongo:27017/
  
  back-end:
    build: 
      context: ../server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ../server:/app/

  front-end:
    build:
      context: ../client
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - /app/node_modules
      - ../client/nginx/nginx.default.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ../client/nginx/cache/:/etc/nginx/cache
      - ../client/certbot/www:/var/www/certbot/:ro
      - ../client/certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
