services:
  pgsql:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build:
      context: ../app
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/
  fileserver:
    build:
      context: ../file_server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ../file_server:/file_server/
