services:
    pgsqlTest:
      image: postgres:16-bullseye
      container_name: pgsqlTest
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d master'"]
        interval: 10s
        timeout: 3s
        retries: 3
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: user
        POSTGRES_DB: master
      ports:
        - 5432:5432