#major.minor.patch
version: "0.0.0"
name: tutorixa

services:
  pgsql:
    image: postgres:16-bullseye
    container_name: pgsql
    restart: always

  app:
    container_name: app
    build: 
      context: ../app
    # depends_on:
    #   - mongo

