#major.minor.patch
version: "0.0.0"
name: tutorixa

services:
  # mongo:
  #   image: mongo:7.0.4-jammy
  #   container_name: mongo
  #   restart: always
  # volumes:
  #   - './data:/data/db'

  app:
    container_name: back-end
    build: 
      context: ../app
    # depends_on:
    #   - mongo



