services:
  pgsql:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  pgsqlTest:
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: master
      POSTGRES_PASSWORD: postgres
    ports:
      - 5431:5432
  app:
    build: 
      context: ../app
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/
  client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ../client:/client/
      - /client/node_modules

