services:
  pgsql:
    environment:
      POSTGRES_USER: usr
      POSTGRES_DB: master
      POSTGRES_PASSWORD: pwd
  
  app:
    build: 
      context: ../app
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ../server:/app/

