name: integration tests
on: push
jobs:
  container-test:
    runs-on: ubuntu-latest
    container: golang:1.21.5-alpine3.18
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: user
          POSTGRES_DB: test
        ports:
          - 5432:5432
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./app/
        run: go mod tidy
        env:
          POSTGRES_HOST: pgsqlTest
          POSTGRES_PORT: 5432

      - name: Run tests
        run: ls -la & pwd & go test .
        
        