name: integration tests
on: push
jobs:
  container-test:
    runs-on: ubuntu-latest
    container: golang:1.21.5-alpine3.18
    defaults:
      run: 
        working-directory: ./app
    services:
      postgres:
        image: postgres:16-bullseye
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: user
          POSTGRES_DB: master
        ports:
          - 5431:5432
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./cmd/test
        
        