name: postgres test container
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: golang:1.21.5-alpine3.18
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: user
        ports:
          - 5432:5432
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./app/
        run: go mod tidy

      - name: Build database
        run: ./app/internal/app/buildtestdb.go
        env:
          POSTGRES_HOST: pgsqlTest
          POSTGRES_PORT: 5432

      - name: Run tests
        run: go test ./..
        
        